export const LINKS = [
  "introduction",
  "map",
  "demographics",
  "exhibitions",
  "word-cloud",
  "gallery-spaces",
  "finding-shows",
  "conclusions",
  "studio-visits",
  "sales",
  "sales-cloud",
  // "sales-platforms-cloud",
  "sales-mediums-cloud",
  "cities-neighborhoods-cloud",
  "studio-visitors-cloud",
  "studio-visit-sources-cloud",
  "websites-social-media",
  "studio-habits",
  "employment",
  "schools",
  "cities",
  "galleries",
  "instructors",
  "closing-thoughts",
  "general-information",
  "exhibitions-opportunities",
  "studio-visits-sales",
  // left-nav-highlighted
  // "word-cloud",
  // general-information
  // exhibitions-opportunities
  // studio-visits-sales
  // websites-social-media
  // studio-habits
  // employment
  // schools
  // cities
  // galleries
  // instructors
  // closing-thoughts
];

export const FINAL_THOUGHTS = [
  { name: "60", value: 1 },
  { name: "collab", value: 1 },
  { name: "wage", value: 1 },
  { name: "you", value: 9 },
  { name: "any", value: 1 },
  { name: "final", value: 1 },
  { name: "thoughts", value: 1 },
  { name: "regarding", value: 1 },
  { name: "thsurvey?", value: 1 },
  { name: "good", value: 2 },
  { name: "job", value: 2 },
  { name: "helpful", value: 3 },
  { name: "am", value: 1 },
  { name: "artist", value: 1 },
  { name: "enjoyed", value: 1 },
  { name: "answering", value: 1 },
  { name: "questions", value: 2 },
  { name: "want", value: 1 },
  { name: "see", value: 4 },
  { name: "more", value: 4 },
  { name: "attention", value: 1 },
  { name: "paid", value: 1 },
  { name: "role", value: 1 },
  { name: "guilt", value: 3 },
  { name: "preconceived", value: 1 },
  { name: "notions", value: 1 },
  { name: "plays", value: 2 },
  { name: "selection", value: 1 },
  { name: "art", value: 7 },
  { name: "all", value: 1 },
  { name: "one", value: 1 },
  { name: "over", value: 1 },
  { name: "often", value: 1 },
  { name: "assumed", value: 1 },
  { name: "individual", value: 1 },
  { name: "has", value: 2 },
  { name: "had", value: 1 },
  { name: "their", value: 3 },
  { name: "opportunity", value: 1 },
  { name: "thus", value: 2 },
  { name: "work", value: 3 },
  { name: "dismissed", value: 1 },
  { name: "younger", value: 1 },
  { name: "artists", value: 5 },
  { name: "emphasized", value: 2 },
  { name: "assumption", value: 1 },
  { name: "completely", value: 2 },
  { name: "ignores", value: 1 },
  { name: "women", value: 1 },
  { name: "who", value: 3 },
  { name: "may", value: 1 },
  { name: "sole", value: 1 },
  { name: "provider", value: 1 },
  { name: "family", value: 1 },
  { name: "unable", value: 1 },
  { name: "even", value: 1 },
  { name: "begparticipate", value: 1 },
  { name: "opportunities", value: 1 },
  { name: "part", value: 2 },
  { name: "tendencies", value: 1 },
  { name: "seen", value: 1 },
  { name: "white", value: 1 },
  { name: "people", value: 1 },
  { name: "make", value: 1 },
  { name: "decisions", value: 1 },
  { name: "based", value: 1 },
  { name: "own", value: 1 },
  { name: "self-centered", value: 1 },
  { name: "effort", value: 1 },
  { name: "relieve", value: 1 },
  { name: "feelings", value: 1 },
  { name: "personal", value: 1 },
  { name: "actual", value: 1 },
  { name: "concern", value: 1 },
  { name: "desire", value: 1 },
  { name: "help", value: 2 },
  { name: "under-represented", value: 1 },
  { name: "groups", value: 1 },
  { name: "result", value: 1 },
  { name: "which", value: 1 },
  { name: "mediocrity", value: 1 },
  { name: "dumbed", value: 1 },
  { name: "down", value: 1 },
  { name: "literature", value: 1 },
  { name: "color", value: 1 },
  { name: "being", value: 1 },
  { name: "patronized", value: 1 },
  { name: "questioning", value: 1 },
  { name: "jurists", value: 1 },
  { name: "directors", value: 1 },
  { name: "suss", value: 1 },
  { name: "thout", value: 1 },
  { name: "should", value: 1 },
  { name: "happy", value: 2 },
  { name: "there", value: 2 },
  { name: "survey", value: 3 },
  { name: "general", value: 1 },
  { name: "interesting", value: 3 },
  { name: "when", value: 1 },
  { name: "where", value: 1 },
  { name: "results", value: 6 },
  { name: "published?", value: 1 },
  { name: "long", value: 2 },
  { name: "seemed", value: 1 },
  { name: "worth", value: 1 },
  { name: "while", value: 1 },
  { name: "felt", value: 1 },
  { name: "very", value: 3 },
  { name: "engaging", value: 1 },
  { name: "not", value: 2 },
  { name: "negative", value: 1 },
  { name: "expecting", value: 1 },
  { name: "wouldn’t", value: 1 },
  { name: "hadn't", value: 1 },
  { name: "written", value: 1 },
  { name: "so", value: 3 },
  { name: "many", value: 2 },
  { name: "notes", value: 1 },
  { name: "suggestions", value: 1 },
  { name: "section", value: 1 },
  { name: ":)", value: 1 },
  { name: "would", value: 4 },
  { name: "juggling", value: 1 },
  { name: "life", value: 1 },
  { name: "partner", value: 1 },
  { name: "and/or", value: 1 },
  { name: "children", value: 1 },
  { name: "full-time", value: 1 },
  { name: "practice", value: 2 },
  { name: "kindlong", value: 1 },
  { name: "nah", value: 1 },
  // { name: "no", value: 10 },
  { name: "thank", value: 9 },
  { name: "collecting", value: 1 },
  { name: "datno", value: 1 },
  { name: "none", value: 1 },
  { name: "everyone", value: 1 },
  { name: "lives", value: 1 },
  { name: "neighborhood", value: 1 },
  { name: "city", value: 1 },
  { name: "reminder", value: 1 },
  { name: "horrible", value: 1 },
  { name: "my", value: 1 },
  { name: "areart", value: 1 },
  { name: "glad", value: 1 },
  { name: "guys", value: 1 },
  { name: "doing", value: 2 },
  { name: "this", value: 2 },
  { name: "your", value: 3 },
  { name: "research", value: 1 },
  { name: "hope", value: 2 },
  { name: "thhelpful", value: 1 },
  { name: "much", value: 2 },
  { name: "creating", value: 1 },
  { name: "thsurvey", value: 2 },
  { name: "looking", value: 1 },
  { name: "forward", value: 1 },
  { name: "brings", value: 1 },
  { name: "about", value: 1 },
  { name: "positive", value: 1 },
  { name: "change", value: 1 },
  { name: "useful", value: 1 },
  { name: "information", value: 1 },
  { name: "findings", value: 1 },
  { name: "putting", value: 1 },
  { name: "thtogether", value: 1 },
  { name: "love", value: 1 },
  { name: "aganext", value: 1 },
  { name: "year", value: 1 },
  { name: "compare", value: 1 },
  { name: "excited", value: 1 },
  { name: "accumulated", value: 1 },
  { name: "better", value: 1 },
  { name: "way", value: 1 },
  { name: "than", value: 1 },
  { name: "gig", value: 1 },
  { name: "economy", value: 1 },
  { name: "squeezing", value: 1 },
  { name: "thvery", value: 1 },
  { name: "cool", value: 1 },
  { name: "take", value: 2 },
  { name: "thpretty", value: 1 },
  { name: "neasurvey", value: 1 },
  { name: "complete", value: 1 },
  { name: "inclusive", value: 1 },
  { name: "like", value: 2 },
  { name: "stress", value: 1 },
  { name: "soul", value: 1 },
  { name: "crushing", value: 1 },
  { name: "try", value: 1 },
  { name: "sell", value: 1 },
  { name: "yes", value: 1 },
  { name: "wish", value: 1 },
  { name: "slink", value: 1 },
  { name: "past", value: 2 },
  { name: "give", value: 1 },
  { name: "credibility", value: 1 },
  { name: "also", value: 1 },
  { name: "promo", value: 1 },
  { name: "mention", value: 1 },
  { name: "you've", value: 1 },
  { name: "used", value: 1 },
  { name: "trusting", value: 1 },
  { name: "person", value: 1 },
  { name: "took", value: 1 },
  { name: "anyway", value: 1 },
  { name: "because", value: 1 },
  { name: "slanted", value: 1 },
  { name: "particular", value: 1 },
  { name: "box", value: 1 },
  { name: "type", value: 1 },
  { name: "thinking", value: 1 },
  { name: "don’t", value: 1 },
  { name: "inaccount", value: 1 },
  { name: "us", value: 1 },
  { name: "self", value: 2 },
  { name: "taught", value: 1 },
  { name: "educated", value: 1 },
  { name: "forced", value: 1 },
  { name: "outside", value: 1 },
  { name: "biz", value: 1 }
]

export const NEGATIVE_SHOUTOUT = [
  { name: "Alaska Government", value: 1 },
  { name: "All of Them", value: 1 },
  { name: "Museums accepting funding from the Sacklers", value: 1 },
  { name: "Money Laundering Galleries / Dealers", value: 1 },
  { name: "Blue Sky Gallery", value: 1 },
  { name: "Carnation Contemporary", value: 1 },
  { name: "College of Marin", value: 1 },
  { name: "SFAI Public Programs", value: 1 },
  { name: "CB1 Gallery", value: 1 },
  { name: "West Valley College", value: 1 },
  { name: "Copyright of the Phrase “Inktober”", value: 1 },
  { name: "Dogwood Arts (Knoxville)", value: 1 },
  { name: "10+ Very Late Payments From Businesses ", value: 1 },
  { name: "Everyone Else", value: 1 },
  { name: "Hauser & Wirth", value: 1 },
  { name: "South Florida Museums / Galleries", value: 1 },
  { name: "Instagram", value: 1 },
  { name: "Facebook", value: 1 },
  { name: "John Natsoulas Gallery", value: 1 },
  { name: "Marciano Art Foundation (LA)", value: 1 },
  { name: "Sparrow Gallery (Sacramento)", value: 1 },
  { name: "Material Institute", value: 1 },
  { name: "Moma PS1", value: 1 },
  // { name: "No", value: 3 },
  // { name: "No ", value: 1 },
  { name: "Governor of Illinois", value: 1 },
  { name: "Onslow Commission on the Arts", value: 1 },
  { name: "NC Arts Council", value: 1 },
  { name: "NEA", value: 1 },
  { name: "Too Many to List", value: 1 }
]

export const POSITIVE_SHOUTOUT = [
  { name: "Aggregate Space Gallery", value: 1 },
  { name: "Anchorage Museum", value: 1 },
  { name: "Art Resources", value: 1 },
  { name: "Burchfield Art Center", value: 1 },
  { name: "ArtCenter Manatee", value: 1 },
  { name: "BBQLA", value: 1 },
  { name: "Boston University Art Galleries", value: 1 },
  { name: "Castledrone", value: 1 },
  { name: "Coaxial", value: 1 },
  { name: "Columbus Cultural Arts Center", value: 1 },
  { name: "Craig Krull Gallery", value: 1 },
  { name: "Dia Beacon", value: 1 },
  { name: "Metropolitan Museum of Art", value: 1 },
  { name: "Gallery 360", value: 1 },
  { name: "Gristle Gallery", value: 1 },
  { name: "Revolution Gallery", value: 1 },
  { name: "Holland Project", value: 1 },
  { name: "Mark Donohue", value: 1 },
  { name: "institutions serve themselves using artists as vehicles", value: 1 },
  { name: "Los Angeles Municipal Art Gallery", value: 1 },
  { name: "Nelson-Atkins", value: 1 },
  // { name: "No", value: 2 },
  { name: "Not a Single One", value: 1 },
  { name: "Not one", value: 1 },
  { name: "Ox-bow School of Art", value: 1 },
  { name: "Painting & Sculpture Outpost", value: 1 },
  { name: "Richmond Art Center", value: 1 },
  { name: "Maturango Museum", value: 1 },
  { name: "Verge Center for the Arts", value: 3 },
  { name: "Jay Jay Gallery", value: 1 },
  { name: "Leimin Space", value: 1 },
  { name: "Charlie James", value: 1 },
  { name: "Project 1612", value: 1 },
  { name: "Iowa City PS1", value: 1 },
  { name: "The Neon Heater", value: 1 },
  { name: "SFA Projects", value: 1 },
  { name: "Nurture Arts", value: 1 },
  { name: "SOHO20", value: 1 },
  { name: "Field Projects", value: 1 },
  { name: "Leslie Lohman", value: 1 },
  { name: "Every Woman’s Biennial", value: 1 },
  { name: "PPOW", value: 1 },
  { name: "Postmasters", value: 1 },
  { name: "Dixon Place", value: 1 },
  { name: "Grace Exhibition Space", value: 1 },
  { name: "Smart Museum of Art", value: 1 },
  { name: "Manetti Shrem Museum", value: 1 },
  { name: "The Bennett Prize", value: 1 },
  { name: "Oliver Art Center", value: 1 },
  { name: "Socrates Sculpture Park", value: 1 },
  { name: "American Academy of Arts and Letters", value: 1 },
  { name: "Journal Gallery", value: 1 },
  { name: "Jack Barrett gallery", value: 1 },
  { name: "Artist Space", value: 1 },
  { name: "Sculpture Center", value: 1 },
  { name: "Gavin Brown Enterprise.", value: 1 },
  { name: "verge art center / studios", value: 1 },
  { name: "Sacramento library zine symposium", value: 1 },
  { name: "Sacramento Zine fest", value: 1 },
  { name: "Axis Gallery", value: 1 },
  { name: "Sol Collective", value: 1 },
  { name: "ArtSpace 1616", value: 1 },
  { name: "Daniel Trejo", value: 1 },
  { name: "Tom Betthauser", value: 1 },
  { name: "Open Art Assignment", value: 1 },
  { name: "Virginia Museum of Fine Arts", value: 1 },
  { name: "VMFA, ICA RVA", value: 1 }
]

export const DISCRIMITATION = [
  {name: "Yes, absolutely", value: ".08"},
  {name: "Yes, I believe so", value: ".14"},
  {name: "Not sure / hard to say", value: ".36"},
  {name: "I don’t believe so", value: ".27"},
  {name: "No, absolutely not", value: ".15"},
]

export const ART_WORLD_WELCOME = [
  {name: "Yes, absolutely", value: ".149"},
  {name: "Yes, Somewhat", value: ".337"},
  {name: "Not sure / hard to say", value: ".198"},
  {name: "No, not particularly", value: ".248"},
  {name: "No, absolutely not", value: ".069"},
]

export const SURVEY_TIME = [
  {name: "1-10", value: ".347"},
  {name: "10-20", value: ".439"},
  {name: "20-30", value: ".194"},
  {name: "30-60", value: ".02"},
  // {name: "60+ min", value: ""},
]

export const EXTRA_DUTY_PAY = [
  {name: "Yes, definitely", value: ".25"},
  {name: "I believe so", value: ".1"},
  {name: "Unsure", value: ".15"},
  {name: "I don't believe so", value: ".2"},
  {name: "No, definitely not", value: ".3"},
]

export const EXTRA_DUTIES = [
  { name: "academic advisor", value: 2 },
  { name: "buying / managing supplies", value: 3 },
  { name: "cleaning classroom", value: 1 },
  { name: "clerical work", value: 1 },
  { name: "committees", value: 1 },
  { name: "department chair", value: 1 },
  { name: "emails in off hours / semesters", value: 1 },
  { name: "faculty navigator", value: 1 },
  { name: "managed art collection", value: 1 },
  { name: "managing hazardous materials", value: 1 },
  { name: "meetings", value: 1 },
  { name: "metal shop teaching", value: 1 },
  { name: "mural painting", value: 2 },
  { name: "NA / none", value: 4 },
  { name: "organizational work", value: 1 },
  { name: "recommendation letters", value: 1 },
  { name: "student / campus exhibitions", value: 1 },
  { name: "teaching free workshops", value: 2 },
  { name: "tech support", value: 1 },
  { name: "theatre sets", value: 1 },
  { name: "volunteer / community events", value: 5 },
  { name: "woodshop teaching", value: 2 }
]

export const UNION_BENEFITS = [
  {name: "yes", value: ".609"},
  {name: "no", value: ".399"},
]

export const UNION_MEMBER = [
  {name: "yes", value: ".208"},
  {name: "no", value: ".771"},
  {name: "not sure", value: ".021"},
]

export const TEACHING_ENVIRONMENT_RATING = [
  { name: "extremely positive", value: "0.129" },
  { name: "generally positive", value: "0.484" },
  { name: "neutral / mixed", value: "0.323" },
  // { name: "generally poor", value: "0" },
  { name: "extremely poor", value: "0.032" },
  { name: "not sure / hard to say", value: "0.032" },
]

export const CAMPUSES_TAUGHT_COUNT = [
  {name: "1", value: ".667"},
  {name: "2", value: ".222"},
  {name: "3", value: ".074"},
  {name: "4", value: ".037"},
  // {name: "4+", value: "0"},
]

export const CLASSES_TAUGHT_COUNT = [
  {name: "1", value: ".481"},
  {name: "2", value: ".111"},
  {name: "3", value: ".148"},
  {name: "4", value: ".185"},
  {name: "5", value: ".074"},
  // {name: "6", value: ""},
  // {name: "6+", value: ""},
]

export const SHOOLS_TAUGHT_AT = [
  { "name": "A Phillip Randolph Highschool", "value": 2 },
  { "name": "Art Supply Demonstrator", "value": 1 },
  { "name": "Artcenter Manatee", "value": 1 },
  { "name": "Ashcan Studio of Art", "value": 1 },
  { "name": "City College of San Francisco (TA)", "value": 1 },
  { "name": "Coastal Carolina Community College", "value": 1 },
  { "name": "College of Marin", "value": 1 },
  { "name": "CSU Long Beach", "value": 1 },
  { "name": "High School", "value": 1 },
  { "name": "Innovations Diploma Prep", "value": 2 },
  { "name": "Long Beach Community College", "value": 1 },
  { "name": "Louisiana State University", "value": 1 },
  { "name": "Material Institute", "value": 1 },
  { "name": "Middle School", "value": 2 },
  { "name": "Molloy College", "value": 2 },
  { "name": "Moreau Catholic High School", "value": 1 },
  { "name": "Msu Broad Art Museum", "value": 1 },
  { "name": "Private Lessons", "value": 1 },
  { "name": "Public Art Center", "value": 1 },
  { "name": "Sacramento City College", "value": 1 },
  { "name": "San Francisco Art Institute (Ta)", "value": 1 },
  { "name": "Sierra College", "value": 1 },
  { "name": "St. Mary’s College of California", "value": 1 },
  { "name": "Tulane", "value": 1 },
  { "name": "Uc Davis", "value": 1 },
  { "name": "Uc Davis Art Museum", "value": 1 },
  { "name": "Uc San Diego", "value": 1 },
  { "name": "University of Alaska Anchorage", "value": 1 },
  { "name": "University of Iowa", "value": 1 },
  { "name": "University of Pittsburgh", "value": 1 },
  { "name": "West Valley College", "value": 1 },
  { "name": "Western Carolina University", "value": 1 },
  { "name": "Youth Art Exchange (SF)", "value": 1 }
]

export const CLOSED_GALLERIES = [
  {name: "0", value: ".317"},
  {name: "1-2", value: ".238"},
  {name: "3-5", value: ".129"},
  {name: "6-10", value: ".01"},
  {name: "10+", value: ".01"},
  {name: "not sure", value: ".297"},
]

export const OPENED_GALLERIES = [
  {name: "0", value: ".317"},
  {name: "1-2", value: ".277"},
  {name: "3-5", value: ".178"},
  {name: "6-10", value: ".01"},
  {name: "10+", value: ".01"},
  {name: "not sure", value: ".208"},
]

export const ART_FAIR_COUNT = [
  {name: "0", value: ".505"},
  {name: "1-2", value: ".356"},
  {name: "3-5", value: ".109"},
  {name: "6-10", value: ".02"},
  {name: "10+", value: ".01"},
  // {name: "not sure", value: ""},
]

export const RECEPTION_COUNT = [
  {name: "0", value: ".139"},
  {name: "1-2", value: ".168"},
  {name: "3-5", value: ".198"},
  {name: "6-10", value: ".188"},
  {name: "11-25", value: ".198"},
  {name: "25-50", value: ".059"},
  {name: "50+", value: ".05"},
]

export const GALLERY_PRIORITY = [
  { name: "extremely important", "value": (31 / 100) },
  { name: "not important", "value": (20 / 100) },
  { name: "somewhat important", "value": (48 / 100) },
  { name: "not sure", "value": (1 / 100) }
]

export const CITY_BENEFITS = [
  { name: "2 Hours To Anywhere", value: 1 },
  { name: "Access To Art", value: 1 },
  { name: "Access To Care As a Trans Person", value: 1 },
  { name: "Access To Cultural Events", value: 1 },
  { name: "Access To Galleries", value: 1 },
  { name: "Access To Hiv Care", value: 1 },
  { name: "Access To Manhattan", value: 1 },
  { name: "Access To Museums", value: 1 },
  { name: "Access To Nature", value: 1 },
  { name: "Access To Public Transportation", value: 1 },
  { name: "Access To Train", value: 1 },
  { name: "Accessibility", value: 1 },
  { name: "Affordability", value: 35 },
  { name: "Aloha Spirit", value: 1 },
  { name: "Art Culture", value: 1 },
  { name: "Art Galleries", value: 1 },
  { name: "Art Schools", value: 1 },
  { name: "Art Stores", value: 1 },
  { name: "Artist Community", value: 1 },
  { name: "Artists", value: 2 },
  { name: "Arts Friendly", value: 1 },
  { name: "Arts Funding", value: 1 },
  { name: "Arts Opportunities", value: 1 },
  { name: "Arts Organizations", value: 1 },
  { name: "Available Space", value: 1 },
  { name: "Beautiful", value: 2 },
  { name: "Beautiful Architecture", value: 1 },
  { name: "Beautiful Area", value: 1 },
  { name: "Beautiful Mountain Views", value: 1 },
  { name: "Beautiful Scenery", value: 1 },
  { name: "Benefit Of Having Lived Here For a While", value: 1 },
  { name: "Blue State", value: 1 },
  { name: "Botanical Gardens", value: 1 },
  { name: "Burgeoning Interest In The Arts/Artists", value: 1 },
  { name: "City Distance", value: 1 },
  { name: "Climate", value: 1 },
  { name: "Close Knit Art Community", value: 1 },
  { name: "Close To Friends", value: 1 },
  { name: "Close To Manhattan", value: 1 },
  { name: "Close To Work", value: 1 },
  { name: "Comfortable", value: 1 },
  { name: "Community", value: 2 },
  { name: "Convenient For Travel", value: 1 },
  { name: "Convenient To Train", value: 1 },
  { name: "Creative", value: 1 },
  { name: "Creative Opportunities.", value: 1 },
  { name: "Culture", value: 1 },
  { name: "Decent Public Transportation", value: 1 },
  { name: "Detroit Is The Best City In The World", value: 1 },
  { name: "Diverse Population", value: 24 },
  { name: "Don’t Need a Car", value: 1 },
  { name: "Easy Access To Other Neighborhoods", value: 1 },
  { name: "Easy Biking Access To Manhattan", value: 1 },
  { name: "Easy To Get Around", value: 1 },
  { name: "Fairly Liberal", value: 1 },
  { name: "Family", value: 1 },
  { name: "Family Close", value: 1 },
  { name: "Family Nearby", value: 1 },
  { name: "Family Vicinity", value: 1 },
  { name: "Far From Large Cities", value: 1 },
  { name: "Fascinating Culture", value: 1 },
  { name: "Friendly", value: 1 },
  { name: "Friends", value: 1 },
  { name: "Fun", value: 1 },
  { name: "Galleries", value: 1 },
  { name: "Gallery", value: 1 },
  { name: "Geographically In a Good Location", value: 1 },
  { name: "Good Airport", value: 1 },
  { name: "Good Arts Community", value: 1 },
  { name: "Good Community", value: 1 },
  { name: "Good Food", value: 5 },
  { name: "Good Neighbors", value: 1 },
  { name: "Good Public Transit", value: 1 },
  { name: "Good Public Transportation", value: 1 },
  { name: "Good Restaurants", value: 1 },
  { name: "Good Schools", value: 2 },
  { name: "Good Transportation", value: 2 },
  { name: "Good Water", value: 1 },
  { name: "Good Weather", value: 10 },
  { name: "Great Art Scene", value: 1 },
  { name: "Great Grocery Store", value: 1 },
  { name: "Great Museum", value: 1 },
  { name: "Great Parks", value: 1 },
  { name: "Great Weather", value: 1 },
  { name: "Hawaiian Culture", value: 1 },
  { name: "Hudson River Light", value: 1 },
  { name: "I Own My Home", value: 1 },
  { name: "Incredible Natural Beauty", value: 1 },
  { name: "Independent Businesses", value: 1 },
  { name: "Inspirational Resources Such As Community  Theaters", value: 1 },
  { name: "Inter Generational", value: 1 },
  { name: "International Airport", value: 1 },
  { name: "Landscape", value: 1 },
  { name: "Large Amount Of Theater", value: 1 },
  { name: "Large Campus", value: 1 },
  { name: "Liberalism", value: 1 },
  { name: "Library", value: 1 },
  { name: "Like-Minded Culture", value: 1 },
  { name: "Literary And Art Community", value: 1 },
  { name: "Local Artist Scene", value: 1 },
  { name: "Local Music Scene", value: 1 },
  { name: "Location", value: 4 },
  { name: "Lots Of Artists", value: 1 },
  { name: "Many Things To Do", value: 1 },
  { name: "Mental Health Center", value: 1 },
  { name: "Mild Weather", value: 1 },
  { name: "Minutes From Downtown", value: 1 },
  { name: "Minutes From Studio", value: 1 },
  { name: "Minutes From The City", value: 1 },
  { name: "Multicultural", value: 1 },
  { name: "Museum", value: 1 },
  { name: "My Town Is Very Artistic", value: 1 },
  { name: "Native Culture", value: 1 },
  { name: "Natural Landscapes", value: 1 },
  { name: "Nature", value: 1 },
  { name: "Nature In My Area", value: 1 },
  { name: "Near Art Resources", value: 1 },
  { name: "Neighbors", value: 1 },
  { name: "None", value: 3 },
  { name: "On a Great Lake", value: 1 },
  { name: "Opportunity", value: 1 },
  { name: "Other Creative People", value: 1 },
  { name: "Parks", value: 1 },
  { name: "Pleasant Environment", value: 1 },
  { name: "Plenty Of Arts", value: 1 },
  { name: "Politically Engaged Community", value: 1 },
  { name: "Population", value: 1 },
  { name: "Price", value: 2 },
  { name: "Proximity To Bay Area", value: 1 },
  { name: "Proximity To La", value: 1 },
  { name: "Proximity To Los Angeles", value: 1 },
  { name: "Proximity To Ocean", value: 1 },
  { name: "Public  Transit", value: 1 },
  { name: "Public Art", value: 1 },
  { name: "Public Transit", value: 1 },
  { name: "Queer Culture", value: 1 },
  { name: "Quiet", value: 6 },
  { name: "Quite", value: 1 },
  { name: "Relaxing", value: 1 },
  { name: "Rent Controlled", value: 1 },
  { name: "Safety", value: 10 },
  { name: "School Distance", value: 1 },
  { name: "Sense Of Community", value: 2 },
  { name: "Small Businesses", value: 1 },
  { name: "Small Town Vibe", value: 1 },
  { name: "Space For Garden", value: 1 },
  { name: "Space For Painting", value: 1 },
  { name: "Temperate Climate", value: 1 },
  { name: "Thriving Art Communities", value: 1 },
  { name: "Thriving Arts Community", value: 1 },
  { name: "Transportation", value: 1 },
  { name: "University Town", value: 1 },
  { name: "Up And Coming Art Scene", value: 1 },
  { name: "Urban", value: 1 },
  { name: "Very Few Thanks To Politics", value: 1 },
  { name: "Vibes", value: 1 },
  { name: "Vibrant Arts Community", value: 1 },
  { name: "Walkability", value: 2 },
  { name: "Walking Ability To City Center", value: 1 },
  { name: "Warmer Weather", value: 1 },
  { name: "Washer Dryer", value: 1 },
  { name: "Weather", value: 2 },
  { name: "Whales", value: 1 },
  { name: "Whole House Instead Of Apartment", value: 1 },
  { name: "Wide Age Range", value: 1 },
  { name: "Wildlife", value: 1 },
  { name: "Woods", value: 1 },
  { name: "Yard", value: 1 },
  { name: "Zoos", value: 1 }
]

export const PREVIOUS_CITY = [
  { name: "AK", value: 1 },
  { name: "Albany", value: 1 },
  { name: "Albuquerque", value: 1 },
  { name: "Anchorage", value: 1 },
  { name: "Bakersfield", value: 1 },
  { name: "baltimore", value: 1 },
  { name: "Baltimore", value: 1 },
  { name: "BC", value: 1 },
  { name: "Beacon", value: 1 },
  { name: "Berkeley", value: 2 },
  { name: "Bloomington", value: 1 },
  { name: "Boise", value: 1 },
  { name: "Boston", value: 1 },
  { name: "Bronx", value: 2 },
  { name: "Brooklyn", value: 2 },
  { name: "CA", value: 6 },
  { name: "California", value: 3 },
  { name: "Canada", value: 1 },
  { name: "Cannonball", value: 1 },
  { name: "Carlisle", value: 1 },
  { name: "Charleston", value: 1 },
  { name: "Charlottesville", value: 1 },
  { name: "Chesterfield/Richmond Virginia", value: 1 },
  { name: "Chicago", value: 3 },
  { name: "Clintonville", value: 1 },
  { name: "Colorado", value: 1 },
  { name: "Columbus", value: 2 },
  { name: "Columbus OH", value: 1 },
  { name: "Congress Heights", value: 1 },
  { name: "Coral Springs", value: 1 },
  { name: "Decatur", value: 1 },
  { name: "Decline to Say", value: 1 },
  { name: "Downtown Lexington", value: 1 },
  { name: "Doylestown", value: 1 },
  { name: "Eagle Rock", value: 1 },
  { name: "East", value: 1 },
  { name: "East Palo Alto", value: 1 },
  { name: "East Side", value: 1 },
  { name: "Eastown", value: 1 },
  { name: "Eastside", value: 1 },
  { name: "Echo Park", value: 2 },
  { name: "Farragut", value: 1 },
  { name: "Floyd", value: 1 },
  { name: "Forida", value: 1 },
  { name: "Franklin MA", value: 1 },
  { name: "Garden District", value: 1 },
  { name: "Georgia", value: 1 },
  { name: "Glendale", value: 1 },
  { name: "Goleta", value: 1 },
  { name: "Grand Rapids", value: 1 },
  { name: "Idaho", value: 1 },
  { name: "IL", value: 1 },
  { name: "Illinois", value: 1 },
  { name: "Indian Beach", value: 1 },
  { name: "Indiana", value: 1 },
  { name: "Kensington", value: 1 },
  { name: "Kitsilano", value: 1 },
  { name: "Knights Bridge", value: 1 },
  { name: "Knoxville", value: 1 },
  { name: "KY", value: 1 },
  { name: "LA", value: 1 },
  { name: "Lafayette", value: 1 },
  { name: "Lakeside", value: 1 },
  { name: "Lincoln", value: 1 },
  { name: "Little Italy", value: 1 },
  { name: "Los Altos", value: 1 },
  { name: "Los Angeles", value: 6 },
  { name: "Los Angeles CA", value: 1 },
  { name: "MA", value: 1 },
  { name: "Madison", value: 1 },
  { name: "Mariposa", value: 1 },
  { name: "maryland", value: 1 },
  { name: "Mattoon", value: 1 },
  { name: "MD", value: 1 },
  { name: "Midtown", value: 1 },
  { name: "Milwaukee", value: 2 },
  { name: "Minneapolis", value: 1 },
  { name: "Monterey", value: 1 },
  { name: "Montreal", value: 1 },
  { name: "Mt. Washington", value: 1 },
  { name: "Nashville", value: 1 },
  { name: "ND", value: 1 },
  { name: "New Orleans", value: 1 },
  { name: "North Beach", value: 1 },
  { name: "North Carolina", value: 1 },
  { name: "North East", value: 1 },
  { name: "New York", value: 9 },
  // { name: "New York", value: 3 },
  // { name: "NY", value: 3 },
  // { name: "NYC", value: 3 },
  { name: "Oak Park", value: 1 },
  { name: "OH", value: 1 },
  { name: "Old North", value: 1 },
  { name: "Oregon", value: 1 },
  { name: "PA", value: 1 },
  { name: "Park Slope", value: 1 },
  { name: "Philadelphia", value: 1 },
  { name: "Pilsen", value: 1 },
  { name: "Pittsburgh", value: 1 },
  { name: "Portland", value: 1 },
  { name: "Providence", value: 1 },
  { name: "Queens", value: 1 },
  { name: "Raeford", value: 1 },
  { name: "Renee’s Lane", value: 1 },
  { name: "RI", value: 1 },
  { name: "Ridgewood", value: 1 },
  { name: "Rogers Park", value: 1 },
  { name: "Rural", value: 1 },
  { name: "Sacramento", value: 4 },
  { name: "Same as 2019", value: 8 },
  { name: "San Francisco", value: 2 },
  { name: "San Jose", value: 1 },
  { name: "Santa Cruz", value: 1 },
  { name: "Sarasota", value: 1 },
  { name: "SC", value: 1 },
  { name: "Silmar", value: 1 },
  { name: "Somerville", value: 1 },
  { name: "South Berkeley", value: 1 },
  { name: "South Buffalo", value: 1 },
  { name: "South Burlington", value: 1 },
  { name: "South Oak Park", value: 1 },
  { name: "South Pasadena", value: 1 },
  { name: "Spring Valley", value: 1 },
  { name: "Standing Rock Reservation", value: 1 },
  { name: "Stockton", value: 1 },
  { name: "Suburban Kansas City", value: 1 },
  { name: "Sylmar", value: 1 },
  { name: "Tennessee", value: 2 },
  { name: "VA", value: 1 },
  { name: "Vancouver", value: 1 },
  { name: "Virginia Beach", value: 1 },
  { name: "VT", value: 1 },
  { name: "Washington DC", value: 1 },
  { name: "Washington Heights", value: 1 },
  { name: "Washington Heigts", value: 1 },
  { name: "West Adams", value: 1 },
  { name: "Westcliffe", value: 1 },
  { name: "WI", value: 1 }
]

export const STUDENT_LOAN_PAYMENT = [
  {name: "$0", value: ".663"},
  {name: "$0 - $50", value: ".011"},
  {name: "$50 - $100", value: ".045"},
  {name: "$100 - $200", value: ".079"},
  {name: "$200 - $300", value: ".056"},
  {name: "$300 - $400", value: ".067"},
  {name: "$400 - $500", value: ".045"},
  {name: "more than $500", value: ".034"},
]

export const STUDENT_LOANS = [
  {name: "$0", value: ".62"},
  {name: "$1 - $5,000", value: ".04"},
  {name: "$5,000 - $20,000", value: ".02"},
  {name: "$20,000 - $50,000", value: ".14"},
  {name: "$50,000 - $100,000", value: ".08"},
  {name: "$100,000 - $200,000", value: ".06"},
  // {name: "More than $200,000", value: ""},
  {name: "Not sure / hard to say", value: ".04"},
]

export const EDUCATION_EXPERIENCE_RATING = [
  {name: "1", value: ".02"},
  // {name: "2", value: "0.0"},
  {name: "3", value: ".041"},
  {name: "4", value: ".02"},
  {name: "5", value: ".102"},
  {name: "6", value: ".112"},
  {name: "7", value: ".194"},
  {name: "8", value: ".204"},
  {name: "9", value: ".143"},
  {name: "10", value: ".163"},
]

export const PAST_DEGREES = [
  { name: "1963", value: 1 },
  { name: "1970", value: 1 },
  { name: "1972", value: 2 },
  { name: "1974", value: 2 },
  { name: "1975", value: 2 },
  { name: "1977", value: 1 },
  { name: "1980", value: 1 },
  { name: "1984", value: 1 },
  { name: "1985", value: 1 },
  { name: "1987", value: 1 },
  { name: "1995", value: 1 },
  { name: "1999", value: 1 },
  { name: "2000", value: 2 },
  { name: "2002", value: 2 },
  { name: "2004", value: 1 },
  { name: "2006", value: 4 },
  { name: "2007", value: 3 },
  { name: "2008", value: 4 },
  { name: "2009", value: 3 },
  { name: "2010", value: 8 },
  { name: "2011", value: 2 },
  { name: "2012", value: 9 },
  { name: "2013", value: 8 },
  { name: "2014", value: 3 },
  { name: "2015", value: 2 },
  { name: "2016", value: 1 },
  { name: "2017", value: 3 },
  { name: "2018", value: 3 },
  { name: "2019", value: 2 },
  { name: "Academy of Art University", value: 1 },
  { name: "AFA", value: 1 },
  { name: "Albany State", value: 1 },
  { name: "American University", value: 1 },
  { name: "Arizona State University", value: 1 },
  { name: "Art", value: 4 },
  { name: "Art Education", value: 5 },
  { name: "Art History", value: 3 },
  { name: "Art Practice", value: 1 },
  { name: "Art Studio", value: 2 },
  { name: "Art Studio and Art History", value: 1 },
  { name: "Art Therapy", value: 2 },
  { name: "Arts & Entertainment Management", value: 1 },
  { name: "AS", value: 1 },
  { name: "BA", value: 14 },
  { name: "Bachelor's", value: 1 },
  { name: "Bachelor's Degree", value: 1 },
  { name: "BBA", value: 1 },
  { name: "BFA", value: 33 },
  { name: "Fine Art", value: 4 },
  { name: "Calarts", value: 4 },
  { name: "BFA Painting", value: 1 },
  { name: "Biology", value: 1 },
  { name: "Biophysics", value: 1 },
  { name: "Brera Academy of Art", value: 1 },
  { name: "BS", value: 10 },
  { name: "California College of The Arts", value: 1 },
  { name: "Cardinal Stritch University", value: 1 },
  { name: "College of Charleston", value: 1 },
  { name: "Communcations", value: 1 },
  { name: "Community Services", value: 1 },
  { name: "Cooper Union", value: 1 },
  { name: "CT", value: 1 },
  { name: "DE", value: 2 },
  { name: "Dean College", value: 1 },
  { name: "Delaware State University Dover", value: 1 },
  { name: "Design & Production", value: 1 },
  { name: "Eastern Kentucky University", value: 1 },
  { name: "Empire State College", value: 1 },
  { name: "Empire State College SUNY", value: 1 },
  { name: "English", value: 1 },
  { name: "Environmental Engineering", value: 1 },
  { name: "Etching and Engraving", value: 1 },
  { name: "FSU", value: 1 },
  { name: "General Studies", value: 1 },
  { name: "Indiana Wesleyan University", value: 1 },
  { name: "Interdisciplinary Visual Arts", value: 1 },
  { name: "Jd Law", value: 1 },
  { name: "Kendall College of Art and Design", value: 1 },
  { name: "MA", value: 5 },
  { name: "Ma", value: 1 },
  { name: "Sculpture", value: 2 },
  { name: "Mason Gross School of Art", value: 1 },
  { name: "Masters Studies", value: 1 },
  { name: "MFA", value: 21 },
  { name: "Painting", value: 14 },
  { name: "Studio Art", value: 4 },
  { name: "Milan Italy", value: 1 },
  { name: "Montclair State", value: 1 },
  { name: "Montclair State MFA", value: 1 },
  { name: "MS", value: 2 },
  { name: "MS Art Education", value: 1 },
  { name: "National Academy", value: 1 },
  { name: "Nazareth College of Rochester", value: 2 },
  { name: "New Haven", value: 1 },
  { name: "New Media", value: 1 },
  { name: "New Paltz State", value: 1 },
  { name: "Newark", value: 1 },
  { name: "No Degree", value: 1 },
  { name: "Nocca", value: 1 },
  { name: "Northern Arizona University", value: 1 },
  { name: "Northern Illinois University", value: 1 },
  { name: "Painting & Wood Sculpture", value: 1 },
  { name: "Painting and Art History", value: 1 },
  { name: "Painting and Printmaking", value: 4 },
  { name: "Phd", value: 1 },
  { name: "Phd Art Education", value: 1 },
  { name: "Photography", value: 1 },
  { name: "Portland State University", value: 1 },
  { name: "Pratt Institute 1972", value: 1 },
  { name: "Printmaking", value: 2 },
  { name: "Psychology", value: 1 },
  { name: "Public Administration", value: 1 },
  { name: "Purchase College", value: 1 },
  { name: "RISD", value: 2 },
  { name: "Rutgers University", value: 1 },
  { name: "Sage College", value: 1 },
  { name: "Salem College", value: 1 },
  { name: "San Francisco Art Institute", value: 11 },
  { name: "San Francisco State University", value: 2 },
  { name: "School of Visual Arts", value: 2 },
  { name: "Self Taught", value: 1 },
  { name: "SMFA", value: 1 },
  { name: "Social Welfare", value: 1 },
  { name: "Stanford University", value: 2 },
  { name: "State Universityat New Paltz NY", value: 1 },
  { name: "Studio Art College of Charleston", value: 1 },
  { name: "Studio Arts", value: 1 },
  { name: "The School of The Museum of Fine Arts", value: 1 },
  { name: "Theatre", value: 1 },
  { name: "Towson University", value: 1 },
  { name: "Tufts University", value: 2 },
  { name: "Tyler School of Art", value: 1 },
  { name: "UC Berkeley", value: 1 },
  { name: "UC Davis", value: 5 },
  { name: "UCLA", value: 1 },
  { name: "UCSB", value: 1 },
  { name: "UIC", value: 1 },
  { name: "University of Delaware", value: 1 },
  { name: "University of Iowa", value: 2 },
  { name: "University of Notre Dame", value: 1 },
  { name: "University of Pittsburgh", value: 1 },
  { name: "University of VA", value: 1 },
  { name: "University of Wisconsin-Madison", value: 3 },
  { name: "University of Wisconsin-Milwaukee", value: 1 },
  { name: "VCU", value: 3 },
  { name: "Visual Arts Studies", value: 1 },
  { name: "Visual Communication", value: 1 },
  { name: "Waynsburg College", value: 1 },
  { name: "Wesleyan University Middletown", value: 1 },
  { name: "Western Michigan", value: 1 },
  { name: "WI", value: 1 },
  { name: "Yale University / School of Art", value: 6 }
]

export const CURRENT_SCHOOL = [
  { name: "An Independent Study Workshop", value: 1 },
  { name: "App Academy", value: 1 },
  { name: "Broward College", value: 1 },
  { name: "Canada College and College of San Mateo", value: 1 },
  { name: "Cecil College", value: 1 },
  { name: "Champlin Park Highschool ", value: 1 },
  { name: "George Washington Carver Center For The Arts and Technology", value: 1 },
  { name: "Illinois State University", value: 1 },
  { name: "Juniata College", value: 1 },
  { name: "Lesley University Low Res Program", value: 1 },
  { name: "Louisiana State University", value: 1 },
  { name: "Macalester College", value: 1 },
  { name: "Massey Hill Classical High School", value: 1 },
  { name: "North County High School", value: 1 },
  { name: "Portland Community College", value: 1 },
  { name: "School of The Art Institute of Chicago", value: 1 },
  { name: "San Francisco Art Institute Mfa Program", value: 1 },
  { name: "The University of Tennessee Knoxville", value: 1 },
  { name: "University of Colorado Boulder", value: 1 },
  { name: "University of Wisconsin-Madison ", value: 1 },
  { name: "Virginia Commonwealth University ", value: 1 },
  { name: "Washington State University", value: 1 },
  { name: "Wayne State University", value: 1 },
  { name: "Western Carolina University", value: 1 },
  { name: "Wilson Middle School", value: 1 },
]

export const CURRENT_STUDENT = [
  {name: "Yes, full time", value: ".21"},
  {name: "Yes, part time", value: ".04"},
  {name: "No", value: ".75"},
]

export const EDUCATION_LEVEL = [
  {name: "Not yet completed High School", value: ".06"},
  {name: "High School Diploma / GED", value: ".02"},
  {name: "Some College", value: ".22"},
  {name: "Some Art School", value: ".03"},
  {name: "Associates Degree", value: ".04"},
  {name: "Bachelors Degree", value: ".12"},
  {name: "BFA", value: ".17"},
  {name: "Masters Degree", value: ".06"},
  {name: "MFA", value: ".26"},
  {name: "PhD", value: ".02"},
]

export const TAX_EXPENSES = [
  {name: "Yes", value: ".307"},
  {name: "No", value: ".554"},
  {name: "Not sure / hard to say", value: ".04"},
  {name: "didn't file 2019 taxes", value: ".099"},
]

export const JOB_INCOME = [
  {name: "$0", value: ".18"},
  {name: "$1 - $5,000", value: ".18"},
  {name: "$5,000 - $15,000", value: ".19"},
  {name: "$15,000 - $25,000", value: ".18"},
  {name: "$25,000 - $50,000", value: ".13"},
  {name: "$50,000 - $75,000", value: ".08"},
  {name: "$75,000 - $100,000", value: ".04"},
  {name: "$100,000 - $150,000", value: ".02"},
  // {name: "more than $150,000", value: ""},
]

export const JOB_APP_COUNT = [
  {name: "0", value: ".47"},
  {name: "1-2", value: ".17"},
  {name: "2-5", value: ".14"},
  {name: "5-10", value: ".07"},
  {name: "10-20", value: ".06"},
  {name: "20+", value: ".09"},
]

export const UNEMPLOYMENT = [
  {name: "yes", value: ".089"},
  {name: "no", value: ".911"},
]

export const JOB_TYPES = [
  { name: "None / full time student", value: 10 },
  { name: "Retail", value: 8 },
  { name: "Restaurant work / server", value: 6 },
  { name: "Teaching", value: 5 },
  { name: "Artist assistant", value: 4 },
  { name: "Babysitter", value: 4 },
  { name: "Teaching art", value: 4 },
  { name: "Adjunct teaching", value: 3 },
  { name: "Adjunct professor", value: 2 },
  { name: "Barista", value: 2 },
  { name: "Commissions", value: 2 },
  { name: "Self-employed", value: 2 },
  { name: "40 hour plus photo shoots", value: 1 },
  { name: "Adjinct faculty", value: 1 },
  { name: "Advertising", value: 1 },
  { name: "Red bubble products", value: 1 },
  { name: "Archivist", value: 1 },
  { name: "Art competition judge", value: 1 },
  { name: "Art conservation", value: 1 },
  { name: "Art handling", value: 1 },
  { name: "Art instructor", value: 1 },
  { name: "Art therapist", value: 1 },
  { name: "Artist", value: 1 },
  { name: "Art related positions", value: 1 },
  { name: "Assisting family business", value: 1 },
  { name: "Cashier and stay at home mom", value: 1 },
  { name: "Ceramics teacher", value: 1 },
  { name: "Coaching", value: 1 },
  { name: "Collections management.", value: 1 },
  { name: "Community college", value: 1 },
  { name: "Community organizing", value: 1 },
  { name: "Cook", value: 1 },
  { name: "Crafts related", value: 1 },
  { name: "Creating art", value: 1 },
  { name: "Curating exhibitions", value: 1 },
  { name: "Customer service", value: 1 },
  { name: "Daycare teacher", value: 1 },
  { name: "Design", value: 1 },
  { name: "Education manager at nonprofit art center", value: 1 },
  { name: "Exhibition tech", value: 1 },
  { name: "Farm stand", value: 1 },
  { name: "Farm work", value: 1 },
  { name: "Freelance art", value: 1 },
  { name: "Freelance film", value: 1 },
  { name: "Freelance high school instructor", value: 1 },
  { name: "Freelance k-12 academic tutor", value: 1 },
  { name: "Freelance web design.", value: 1 },
  { name: "Freelance work", value: 1 },
  { name: "Frontline representative at an art museum", value: 1 },
  { name: "Full-time museum professional", value: 1 },
  { name: "Full-time professional relations for state", value: 1 },
  { name: "Gallery assisting", value: 1 },
  { name: "Gallery guard", value: 1 },
  { name: "Gallery invigilator", value: 1 },
  { name: "General merchandise with target", value: 1 },
  { name: "Gigs", value: 1 },
  { name: "Grad student", value: 1 },
  { name: "Graduate assisant", value: 1 },
  { name: "Graduate teaching associate", value: 1 },
  { name: "I receive social security", value: 1 },
  { name: "I work at harvard full time", value: 1 },
  { name: "I’m freelance", value: 1 },
  { name: "Instructor", value: 1 },
  { name: "Janitor", value: 1 },
  { name: "Kinesiology camp staff", value: 1 },
  { name: "Laboratory assistant", value: 1 },
  { name: "Lawyer", value: 1 },
  { name: "Maintenance person for art residency", value: 1 },
  { name: "Making and selling my art", value: 1 },
  { name: "Marketing / advertising", value: 1 },
  { name: "Mfa student work", value: 1 },
  { name: "Muralist teaching artist", value: 1 },
  { name: "Museum attendant", value: 1 },
  { name: "Museum preparator", value: 1 },
  { name: "Museum visitor services", value: 1 },
  { name: "Musician", value: 1 },
  { name: "N/a", value: 1 },
  { name: "News reporter", value: 1 },
  { name: "No jobs", value: 1 },
  { name: "No outside jobs", value: 1 },
]

export const STUDIO_HOURS = [
  // {name: "Less than 1 hour", value: ""},
  {name: "1-2", value: ".069"},
  {name: "2-5", value: ".455"},
  {name: "5-7", value: ".198"},
  {name: "7-10", value: ".109"},
  {name: "10+", value: ".089"},
  {name: "N/A", value: ".079"},
]

export const STUDIO_DAYS = [
  {name: "NA", value: ".08"},
  {name: "<1", value: ".04"},
  {name: "1", value: ".05"},
  {name: "2", value: ".11"},
  {name: "3", value: ".18"},
  {name: "4", value: ".15"},
  {name: "5", value: ".17"},
  {name: "6", value: ".09"},
  {name: "7", value: ".13"},
]

export const STUDIO_PRICE = [
  {name: "studio mixed with living space", value: ".429"},
  {name: "$0", value: ".235"},
  {name: "$0 - $100", value: ".02"},
  {name: "$101 - $250", value: ".071"},
  {name: "$250 - $500", value: ".102"},
  {name: "$501 - $750", value: ".071"},
  {name: "$751 - $1,000", value: ".02"},
  {name: "$1,001 - $2,500", value: ".01"},
  {name: "$2,500 - $5,000", value: ".01"},
  // {name: "More than $5,000", value: "0.0"},
  {name: "Not sure / hard to say", value: ".031"},
]

export const STUDIO_SIZE = [
  {name: "Not sure / hard to say", value: ".071"},
  {name: "A desk / table etc. (< 80 ft^2)", value: ".303"},
  {name: "About 8 by 10 feet (80 ft^2)", value: ".141"},
  {name: "About 10 by 15 feet (150 ft^2)", value: ".202"},
  {name: "About 15 by 20 feet (300 ft^2)", value: ".141"},
  {name: "About 20 by 30 feet (600 ft^2)", value: ".061"},
  {name: "More than 20 by 30 feet (600+ ft^2)", value: ".081"},
]

export const STUDIO_SPACE_TYPE = [
  {name: "Dedicated room / desk / area in living space", value:	(48 / 163)},
  {name: "Completely mixed up with living space", value:	(45 / 163)},
  {name: "Private studio space", value:	(19 / 163)},
  {name: "Space provided by a school / residency etc.", value:	(16 / 163)},
  {name: "Shared studio split with another artist / artists", value:	(13 / 163)},
  {name: "Studio in a larger studio building", value:	(11 / 163)},
  {name: "Alternative space in non-studio building", value:	(7 / 163)},
  {name: "Other", value:	(4 / 163)},
  // {name: "Dedicated room / desk / area in living space", value:	48},
  // {name: "Completely mixed up with living space", value:	45},
  // {name: "Private studio space", value:	19},
  // {name: "Space provided by a school / residency etc.", value:	16},
  // {name: "Shared studio split with another artist / artists", value:	13},
  // {name: "Studio in a larger studio building", value:	11},
  // {name: "Alternative space in non-studio building", value:	7},
  // {name: "Other", value:	4},
]

export const ART_RESOURCES = [
  { name: "Instagram", value: 90 },
  { name: "Google Images", value: 43 },
  { name: "Facebook", value: 35 },
  { name: "Hyperallergic", value: 33 },
  { name: "ARTnews", value: 28 },
  { name: "New York Times (Arts)", value: 25 },
  { name: "Art Forum", value: 24 },
  { name: "Pintrist", value: 22 },
  { name: "Art in America", value: 21 },
  { name: "Twitter", value: 19 },
  { name: "The New Yorker", value: 16 },
  { name: "Reddit", value: 15 },
  { name: "New York Magazine", value: 14 },
  { name: "Hi-Fructose", value: 12 },
  { name: "Brooklyn Rail", value: 11 },
  { name: "New American Paintings", value: 11 },
  { name: "Contemporary Art Daily", value: 9 },
  { name: "LA Times (Arts & Culture)", value: 8 },
  { name: "Carla", value: 7 },
  { name: "Frieze Magazine", value: 5 },
  { name: "SFAQ / NYAQ / LXAQ", value: 5 },
  { name: "Art F City", value: 2 },
  { name: "Galleries", value: 2 },
  { name: "Museums", value: 2 },
  { name: "Art in Context", value: 1 },
  { name: "artist pages", value: 1 },
  { name: "Artrabbit app NY artbeats app", value: 1 },
  { name: "artstor", value: 1 },
  { name: "artsy", value: 1 },
  { name: "Carlisle Arts Learning Center", value: 1 },
  { name: "college libraries", value: 1 },
  { name: "Deviantart", value: 1 },
  { name: "Discord art groups", value: 1 },
  { name: "Ello", value: 1 },
  { name: "fine art connoisseur", value: 1 },
  { name: "follower posts", value: 1 },
  { name: "gallery pages.", value: 1 },
  { name: "International Artist", value: 1 },
  { name: "Juxtapoz", value: 1 },
  { name: "LA Weekly", value: 1 },
  { name: "Larry’s List", value: 1 },
  { name: "Linkedin", value: 1 },
  { name: "my nose", value: 1 },
  { name: "None lol", value: 1 },
  { name: "public library", value: 1 },
  { name: "TikTok", value: 1 },
  { name: "Tumblr", value: 1 },
  { name: "Two Coats of Paint", value: 1 },
  { name: "Various art group pages", value: 1 },
  { name: "YouTube", value: 1 },
]

export const PERSONAL_WEBSITE_2016 = [
  {name: "yes", value: ".515"},
  {name: "no", value: ".434"},
  {name: "can't recall", value: ".051"},
]

export const PERSONAL_WEBSITE = [
  {name: "Yes and I plan to continue", value: ".7"},
  {name: "Yes but I plan to stop", value: ".01"},
  {name: "No but I plan to make one", value: ".2"},
  {name: "No and I have no plans to doso", value: ".09"},
]

export const SOCIAL_MEDIA_NEGATIVES = [
  { name: "Likes", value: 2 },
  { name: "order of posts", value: 2 },
  { name: "Algorithms", value: 3 },
  { name: "algorithm works against artists who don’t post as often", value: 1 },
  { name: "All", value: 1 },
  { name: "basically everything", value: 1 },
  { name: "Consciousness is very short online", value: 1 },
  { name: "cropping", value: 1 },
  { name: "deciding which pieces to post", value: 1 },
  { name: "Did little to generate sales", value: 1 },
  { name: "engagement", value: 1 },
  { name: "Event rsvp", value: 1 },
  { name: "everything", value: 1 },
  { name: "exposes artworld exclusivity and worthlessness of own art", value: 1 },
  { name: "Facebook", value: 1 },
  { name: "favoring likes", value: 1 },
  { name: "Favoritism and nepotism", value: 1 },
  { name: "Few substantive comments", value: 1 },
  { name: "Follower Counts", value: 1 },
  { name: "Follower numbers", value: 1 },
  { name: "followers", value: 1 },
  { name: "getting posts out to others", value: 1 },
  { name: "has become something i will not use", value: 1 },
  { name: "I could be better at posting daily", value: 1 },
  { name: "i dont have an art instagram", value: 1 },
  { name: "I have no reach", value: 1 },
  { name: "Idk", value: 1 },
  { name: "instagram software", value: 1 },
  { name: "Instagram’s algorithm", value: 1 },
  { name: "Looking instead of making", value: 1 },
  { name: "My work is physical", value: 1 },
  { name: "my work is slower to make", value: 1 },
  { name: "non-chronological posts in feed", value: 1 },
  { name: "non-linear algorithms", value: 1 },
  { name: "not for sharing with public", value: 1 },
  { name: "Not sure", value: 1 },
  { name: "Nothing", value: 1 },
  { name: "number of posts", value: 1 },
  { name: "oversaturstion of imagery", value: 1 },
  { name: "Personal issues", value: 1 },
  { name: "posts no longer appear if not famous or paid", value: 1 },
  { name: "really boring in general", value: 1 },
  { name: "Referencing", value: 1 },
  { name: "Seems to work", value: 1 },
  { name: "so the whole thing is problematic", value: 1 },
  { name: "the algorithms are completely rigged", value: 1 },
  { name: "The new algorithm", value: 1 },
  { name: "to get optimum reach", value: 1 },
  { name: "Unsolicited ads", value: 1 },
  { name: "unthoughtful viewership", value: 1 },
  { name: "very small percentage of followers see posts", value: 1 },
]

export const SOCIAL_MEDIA_POSITIVES = [
  { name: "Follower counts", value: 3 },
  { name: "Followers", value: 3 },
  { name: "likes", value: 5 },
  { name: "Public Likes", value: 7 },
  { name: "Building followers", value: 1 },
  { name: "Comments", value: 1 },
  { name: "Connected with other artists", value: 1 },
  { name: "did nothing", value: 1 },
  { name: "Direct contact", value: 1 },
  { name: "Direct messages from buyers", value: 1 },
  { name: "direct messaging", value: 1 },
  { name: "direct messaging other artists", value: 1 },
  { name: "distracted me", value: 1 },
  { name: "do not use social media", value: 1 },
  { name: "Expanding audience", value: 1 },
  { name: "feed back from followers", value: 1 },
  { name: "Feedback from wider audience", value: 1 },
  { name: "Follower engagement page", value: 1 },
  { name: "friendly", value: 1 },
  { name: "Getting name recognized", value: 1 },
  { name: "global Connections to artists", value: 1 },
  { name: "global exposure", value: 1 },
  { name: "good feedback", value: 1 },
  { name: "has almost ruined me", value: 1 },
  { name: "I don’t think it did", value: 1 },
  { name: "I saw no tangible benefits", value: 1 },
  { name: "Idk", value: 1 },
  { name: "likes and followers", value: 1 },
  { name: "made sales", value: 1 },
  { name: "more my interactions with people", value: 1 },
  { name: "Motivation and inspiration", value: 1 },
  { name: "Networking", value: 1 },
  { name: "New followers/exposure", value: 1 },
  { name: "None", value: 1 },
  { name: "Not sure", value: 1 },
  { name: "Nothing at all", value: 1 },
  { name: "online gallery space", value: 1 },
  { name: "organizations contact", value: 1 },
  { name: "photo sharing", value: 1 },
  { name: "Posting regularly", value: 1 },
  { name: "process / studio environment stories", value: 1 },
  { name: "Reaching a new audiences", value: 1 },
  { name: "Receiving validation", value: 1 },
  { name: "Recognition through exposure", value: 1 },
  { name: "reposting", value: 1 },
  { name: "reposting my posts", value: 1 },
  { name: "Reposts from more established artists", value: 1 },
  { name: "sharing posts via instagram stories", value: 1 },
  { name: "simple layout", value: 1 },
]

export const SALE_TYPES = [
  { name: "Instagram", value: 35 },
  { name: "galleries", value: 29 },
  { name: "studio visits", value: 22 },
  { name: "events", value: 18 },
  { name: "Facebook", value: 14 },
  { name: "art dealers", value: 6 },
  { name: "Etsy", value: 3 },
  { name: "in person", value: 2 },
  { name: "Website", value: 2 },
  { name: "and makers fairs)", value: 1 },
  { name: "art fairs", value: 1 },
  { name: "Art markets", value: 1 },
  { name: "Artomat project", value: 1 },
  { name: "Auction Sales", value: 1 },
  { name: "Bandcamp", value: 1 },
  { name: "Book fairs", value: 1 },
  { name: "businesses / resaurants", value: 1 },
  { name: "Commissioned trades", value: 1 },
  { name: "Cultivating personal relationships", value: 1 },
  { name: "did not", value: 1 },
  { name: "direct to client", value: 1 },
  { name: "Discord", value: 1 },
  { name: "Fundraising auction", value: 1 },
  { name: "holiday sales", value: 1 },
  { name: "I don’t sell my art", value: 1 },
  { name: "networking", value: 1 },
  { name: "newsletter", value: 1 },
  { name: "No sales", value: 1 },
  { name: "online", value: 1 },
  { name: "online store", value: 1 },
  { name: "phone calls", value: 1 },
  { name: "Pop-up shops", value: 1 },
  { name: "Redbubble", value: 1 },
  { name: "shows", value: 1 },
  { name: "Shows", value: 1 },
  { name: "sold through collectors", value: 1 },
  { name: "Sold work at book fairs", value: 1 },
  { name: "Sold work through competition", value: 1 },
  { name: "studio sale", value: 1 },
  { name: "tattoo shop", value: 1 },
]

export const SOCIAL_MEDIA_SERVICE_RATING = [
  { name: "0", value: ".067"},
  {name: "1", value: ".067"},
  {name: "2", value: ".117"},
  {name: "3", value: ".083"},
  {name: "4", value: ".083"},
  {name: "5", value: ".117"},
  {name: "6", value: ".117"},
  {name: "7", value: ".217"},
  {name: "8", value: ".067"},
  { name: "9", value: ".017"},
  {name: "10", value: ".05"},
]

export const PAID_SOCIAL_MEDIA = [
  {name: "didn't pay for any promo", value: "0.792"},
  {name: "paid for promo but no impact", value: "0.099"},
  {name: "paid for promo with some impact", value: "0.069"},
  {name: "paid for promo with large impact", value: "0.01"},
  {name: "not sure / don’t recall", value: "0.03"},
]

export const INSTAGRAM_MORE_LESS = [
  {name: "A lot more", value: "0.3"},
  {name: "Somewhat more", value: "0.33"},
  {name: "About the same", value: "0.2"},
  {name: "Somewhat less", value: "0.11"},
  {name: "A lot less", value: "0.02"},
  {name: "Not sure / hard to say", value: "0.04"},
]

export const FACEBOOK_MORE_LESS = [
  {name: "A lot more", value: "0.042"},
  {name: "Somewhat more", value: "0.125"},
  {name: "About the same", value: "0.271"},
  {name: "Somewhat less", value: "0.125"},
  {name: "A lot less", value: "0.333"},
  {name: "Not sure / hard to say", value: "0.104"},
]

export const INSTAGRAM_FREQUENCY = [
  {name: "Never", value: "0.03"},
  {name: "Almost never", value: "0.03"},
  {name: "1-3 times per year", value: "0.129"},
  {name: "1-3 times per month", value: "0.416"},
  {name: "1-3 times per week", value: "0.287"},
  {name: "1-3 times per day", value: "0.099"},
  {name: "More than 3 times perday", value: "0.01"},
]

export const FACEBOOK_POST_FREQUENCY = [
  {name: "Never", value: "0.384"},
  {name: "Almost never", value: "0.091"},
  {name: "1-3 times per year", value: "0.162"},
  {name: "1-3 times per month", value: "0.141"},
  {name: "1-3 times per week", value: "0.172"},
  {name: "1-3 times per day", value: "0.03"},
  {name: "More than 3 times perday", value: "0.02"},
]

export const SOC_MEDIA_PRIORITY = [
  { name: "not sure / hard to say", value: "0.059" },
  { name: "extremely important", value: "0.396" },
  { name: "somewhat important", value: "0.416" },
  { name: "not important", value: "0.129" },
]

export const STUDIO_VISIT_SOURCES = [
  { name: "Other artist peers", value: 30 },
  { name: "Conversations at openings / receptions", value: 29 },
  { name: "Teachers / faculty", value: 15 },
  { name: "Direct messages on Instagram", value: 12 },
  { name: "BFA / MFA peers", value: 10 },
  { name: "Being cold contacted by others", value: 9 },
  { name: "Direct emails messages", value: 8 },
  { name: "Direct messages on Facebook", value: 7 },
  { name: "Cold contacting others", value: 3 },
  { name: "Annual “art hop” event", value: 1 },
  { name: "but just because they need to to their work in a studio?", value: 1 },
  { name: "Drop by unannounced", value: 1 },
  { name: "Friends of friends", value: 1 },
  { name: "I have a public-facing studio in a highly trafficked ares", value: 1 },
  { name: "Invited artist friends over to see my studio space.", value: 1 },
  { name: "Last time I checked an artist wouldn’t go for anyone else", value: 1 },
  { name: "Listing in regional brochure", value: 1 },
  { name: "Local audio tour", value: 1 },
  { name: "na", value: 1 },
  { name: "open studio event", value: 1 },
  { name: "Participating in formal city wise studio tour", value: 1 },
  { name: "People come to visit the facility  I’m working in", value: 1 },
  { name: "Phone and actual conversations", value: 1 },
  { name: "Studio is in an art guild", value: 1 },
]

export const STUDIO_VISITORS = [
  { name: "Other artists", value: 46 },
  { name: "Family / non-artist friends", value: 30 },
  { name: "Gallerists / curators", value: 21 },
  { name: "Amateur / new collectors", value: 19 },
  { name: "BFA / MFA peers", value: 13 },
  { name: "Established / experienced collectors", value: 13 },
  { name: "Former / current faculty", value: 10 },
  { name: "Open studios", value: 2 },
  { name: "students", value: 2 },
  { name: "Community members", value: 1 },
  { name: "general public", value: 1 },
  { name: "na", value: 1 },
  { name: "Press", value: 1 },
]

export const SIDE_NOTES = {
  "word-cloud": "* relative size of words based on how many times they appeared in survey responses",
  "gallery-spaces": "* relative size of words based on how many times they appeared in survey responses",
  "finding-shows": "* relative size of words based on how many times they appeared in survey responses",
}

export const CITIES_NEIGHBORHOODS = [
  { name: 'Albany (CA)', value: 1 },
  { name: 'Albuquerque', value: 2 },
  { name: 'Altadena (CA)', value: 1 },
  { name: 'Anchorage', value: 1 },
  { name: 'Atlanta', value: 1 },
  { name: 'Bakersfield', value: 1 },
  { name: 'Baltimore', value: 2 },
  { name: 'Baton Rouge (LA)', value: 1 },
  { name: 'Beacon', value: 1 },
  { name: 'Berkeley', value: 2 },
  { name: 'Bloomington', value: 1 },
  { name: 'Bronx Nyc', value: 1 },
  { name: 'Brooklyn', value: 3 },
  { name: 'Buffalo', value: 1 },
  { name: 'Capitola', value: 1 },
  { name: 'Carlisle', value: 1 },
  { name: 'Central Phoenix', value: 1 },
  { name: 'Chesterfield', value: 1 },
  { name: 'Chicago', value: 2 },
  { name: 'Chippewa Falls', value: 1 },
  { name: 'Columbus', value: 3 },
  { name: 'Congress Heights (DC)', value: 1 },
  { name: 'Coral Springs (FL)', value: 1 },
  { name: 'Corktown', value: 1 },
  { name: 'Creston', value: 1 },
  { name: 'Decline To Say', value: 1 },
  { name: 'Detroit', value: 1 },
  { name: 'Downtown Lexington', value: 1 },
  { name: 'East Palo Alto', value: 1 },
  { name: 'Eastside', value: 1 },
  { name: 'Echo Park', value: 3 },
  { name: 'Edgewood', value: 1 },
  { name: 'Fayetteville', value: 1 },
  { name: 'Florida Indian Beach', value: 1 },
  { name: 'Grand Rapids', value: 1 },
  { name: 'Jacksonville', value: 1 },
  { name: 'Kihei', value: 1 },
  { name: 'Knights Bridge', value: 1 },
  { name: 'Knoxville', value: 1 },
  { name: 'Lafayette', value: 1 },
  { name: 'Lake Ann (MI)', value: 1 },
  { name: 'Lake Toxaway', value: 1 },
  { name: 'Lake Zurich', value: 1 },
  { name: 'Lincoln Heights', value: 1 },
  { name: 'Long Beach', value: 1 },
  { name: 'Los Angeles', value: 6 },
  { name: 'Macalester-Groveland (MN)', value: 1 },
  { name: 'Madison', value: 2 },
  { name: 'Malvern', value: 1 },
  { name: 'Massey Hill', value: 1 },
  { name: 'Maui', value: 1 },
  { name: 'Meredith (NH)', value: 1 },
  { name: 'Miami', value: 1 },
  { name: 'Mile End Montreal', value: 1 },
  { name: 'Milo-Grogan', value: 1 },
  { name: 'Milwaukee', value: 2 },
  { name: 'Monroe Ward', value: 1 },
  { name: 'Monrovia', value: 1 },
  { name: 'Murray', value: 1 },
  { name: 'Nashville', value: 1 },
  { name: 'Natomas', value: 2 },
  { name: 'New Brighton State Beach', value: 1 },
  { name: 'New Haven', value: 1 },
  { name: 'New Orleans', value: 1 },
  { name: 'New York', value: 8 },
  { name: 'Normal (IL)', value: 1 },
  { name: 'North Beach', value: 1 },
  { name: 'North East Lakeside', value: 1 },
  { name: 'North Oak Park', value: 1 },
  { name: 'Oak Park', value: 2 },
  { name: 'Old Irving Park', value: 1 },
  { name: 'Park Slope', value: 1 },
  { name: 'Philadelphia', value: 1 },
  { name: 'Pittsburgh', value: 1 },
  { name: 'Portland', value: 1 },
  { name: 'Pullman (Wa)', value: 1 },
  { name: 'Richmond (VA)', value: 3 },
  { name: 'Rural Elton (LA)', value: 1 },
  { name: 'Sacramento', value: 6 },
  { name: 'Saint Paul', value: 1 },
  { name: 'San Francisco', value: 2 },
  { name: 'San Jose', value: 1 },
  { name: 'Santa Fe', value: 1 },
  { name: 'Sarasota', value: 1 },
  { name: 'Saugatuck', value: 1 },
  { name: 'Seattle', value: 1 },
  { name: 'Somerville (MA)', value: 1 },
  { name: 'South Buffalo', value: 1 },
  { name: 'South Burlington (VT)', value: 1 },
  { name: 'South Oak Park', value: 1 },
  { name: 'South Philadelphia', value: 1 },
  { name: 'Southeast Portland', value: 1 },
  { name: 'Spring Hill', value: 1 },
  { name: 'Stockton', value: 1 },
  { name: 'Suburban Kansas City', value: 1 },
  { name: 'Tecopa', value: 1 },
  { name: 'The Bronx', value: 2 },
  { name: 'Washington Heights', value: 1 },
  { name: 'Westcliffe (CO)', value: 1 },
  { name: 'Wrigleyvalue', value: 1 },
]

export const VISIT_COUNT = [
  { name: "not sure / hard to say", value: "0.04" },
  { name: "0", value: "0.396" },
  { name: "1-2", value: "0.188" },
  { name: "3-5", value: "0.178" },
  { name: "5-10", value: "0.069" },
  { name: "10-25", value: "0.069" },
  { name: "25+", value: "0.069" },
];

export const VISIT_PRIORITY = [
  { name: "not sure / hard to say", value: "0.059" },
  { name: "extremely important", value: "0.149" },
  { name: "somewhat important", value: "0.257" },
  { name: "not important", value: "0.525" },
];

export const COLLECTOR_TREATMENT = [
  { name: "not sure / hard to say", value: "0.061" },
  { name: "did not sell work", value: "0.143" },
  { name: "extremely positive", value: "0.344" },
  { name: "generally positive", value: "0.378" },
  { name: "neutral / mixed", value: "0.051" },
  { name: "generally poor", value: "0.02" },
  { name: "extremely poor", value: "0.00" },
];

export const SALES_MEDIUMS = [
  { name: "Paintings",	value: 42 },
  { name: "T-Shirts",	value: 14 },
  { name: "Prints",	value: 13 },
  { name: "Drawings",	value: 11 },
  { name: "Stickers",	value: 7 },
  { name: "Pins",	value: 4 },
  { name: "Books",	value: 3 },
  { name: "Mixed Media",	value: 3 },
  { name: "Sketches",	value: 3 },
  { name: "Zines",	value: 3 },
  { name: "Cards",	value: 2 },
  { name: "Designs",	value: 2 },
  { name: "Digital Prints",	value: 2 },
  { name: "Magnets",	value: 2 },
  { name: "Photographs",	value: 2 },
  { name: "Sculpture",	value: 2 },
];

export const SALES_SUM = [
  { name: "$0", value: "0.14" },
  { name: "$1-$50", value: "0.13" },
  { name: "$50-$250", value: "0.13" },
  { name: "$250-$500", value: "0.14" },
  { name: "$500-$1,000", value: "0.16" },
  { name: "$1,000-$2,500", value: "0.12" },
  { name: "$2,500-$5,000", value: "0.13" },
  { name: "$5,000-$10,000", value: "0.01" },
  { name: "$10,000-$25,000", value: "0.01" },
  { name: "$25,000-$50,000", value: "0.02" },
  { name: "$$50,000+", value: "0.01" },
];

export const ANY_ONLINE_SALES = [
  { name: "no", value: "0.633" },
  { name: "yes", value: "0.367" },
];

export const SALE_PLATFORMS = [
  { name: "No Online Sales", value: (63 / 101) },
  { name: "Etsy", value: (11 / 101) },
  { name: "Saatchi Art", value: (3 / 101) },
  { name: "Art Finder", value: (2 / 101) },
  { name: "BigCartel", value: (2 / 101) },
  { name: "Red Bubble", value: (2 / 101) },
  { name: "Art in Context", value: (1 / 101) },
  { name: "Artery", value: (1 / 101) },
  { name: "Artsy", value: (1 / 101) },
  { name: "Bandcamp", value: (1 / 101) },
  { name: "Deviantart", value: (1 / 101) },
  { name: "SquareUp", value: (1 / 101) },
  { name: "Facebook", value: (1 / 101) },
  { name: "Fine Art America", value: (1 / 101) },
  { name: "Fiverr", value: (1 / 101) },
  { name: "Instagram", value: (1 / 101) },
  { name: "Padel 8", value: (1 / 101) },
  { name: "Personal Website", value: (1 / 101) },
  { name: "Printful", value: (1 / 101) },
  { name: "Square Space", value: (1 / 101) },
  { name: "Wix", value: (1 / 101) },
  { name: "Wordpress Website", value: (1 / 101) },
]

export const BUYERS_CLOUD = [
  { name: 'Amateur / New Collectors', value: 35 },
  { name: 'Art Center Store In Consignment', value: 1 },
  { name: 'Artomat Machines', value: 1 },
  { name: 'Book Fair', value: 2 },
  { name: 'BFA / MFA Peers', value: 8 },
  { name: 'Established / Experienced Collectors', value: 20 },
  { name: 'Event Attendants', value: 1 },
  { name: 'Event Attendees', value: 31 },
  { name: 'Family / Friends', value: 62 },
  { name: 'Former / Current Faculty', value: 7 },
  { name: 'Gallerists / Curators', value: 6 },
  { name: 'Gallery Clients', value: 1 },
  { name: 'I Don’t Sell My Art', value: 1 },
  { name: 'Interior Designer For Client', value: 1 },
  { name: 'My Financial Advisor', value: 1 },
  { name: 'Nobody', value: 1 },
  { name: 'None', value: 2 },
  { name: 'Online Fans', value: 31 },
  { name: 'Other Artists', value: 34 },
  { name: 'Strangers', value: 1 },
  { name: 'Youtubers (Animation Assets)', value: 1 },
]

export const SELLLING_PRIORITY = [
  { name: "Not Sure / Hard to Say", value: "0.03" },
  { name: "Not Important", value: "0.202" },
  { name: "Somewhat Important", value: "0.434" },
  { name: "Extremely Important", value: "0.323" },
];

export const GRANT_SUM = [
  { name: "no applications", value: "0.51" },
  { name: "$0", value: "0.39" },
  { name: "$1-$500", value: "0.02" },
  { name: "$500-$5,000", value: "0.07" },
  { name: "$5,000-$15,000", value: "0.01" },
];

export const GRANT_COUNT = [
  { name: "no applications", value: "0.55" },
  { name: "0", value: "0.34" },
  { name: "1-2", value: "0.11" },
];

export const GRANT_APP_COUNT = [
  { name: "0", value: "0.713" },
  { name: "1-2", value: "0.218" },
  { name: "3-5", value: "0.059" },
  { name: "", value: "0.01" },
];

export const RESIDENCY_COUNT = [
  { name: "no applications", value: "0.475" },
  { name: "0", value: "0.434" },
  { name: "1-2", value: "0.091" },
]

export const RESIDENCY_APP_COUNT = [
  { name: "0", value: "0.723" },
  { name: "1-2", value: "0.218" },
  { name: "3-5", value: "0.05" },
  { name: "6-10", value: "0.01" },
]

export const RESIDENCY_PRIORITY = [
  { name: "Not Sure / Hard to Say", value: "0.112" },
  { name: "Not Important", value: "0.49" },
  { name: "Somewhat Important", value: "0.286" },
  { name: "Extremely Important", value: "0.112" },
];

export const LEGAL_PAPERWORK = [
  { name: "no", value: "0.624" },
  { name: "yes (with explaination)", value: "0.287" },
  { name: "yes (not fully explained)", value: "0.059" },
  { name: "not sure / don't recall", value: "0.03" },
]

export const GALLERY_REPRESENTATION = [
  { name: "no", value: "0.83" },
  { name: "yes", value: "0.17" },
]

export const EVENT_ORGANIZATION = [
  { name: "0", value: "0.554" },
  { name: "1", value: "0.178" },
  { name: "2", value: "0.129" },
  { name: "3", value: "0.079" },
  { name: "4", value: "0.02" },
  { name: "5+", value: "0.04" },
]

export const COLORS = [
  "rgb(216, 159, 202)",
  "rgb(247, 193, 209)",
  "#FFB7B2",
  "rgb(252, 210, 183)",
  "rgb(188, 223, 132)",
  "rgb(166, 226, 204)",
  "rgb(158, 171, 226)",
]

export const EXHIBITION_CONTACT = [
    { name: 'Art Council Research', value: (1 / 201) },
    { name: 'Non Profit Gallery', value: (1 / 201) },
    { name: 'Art Societies', value: (2 / 201) },
    { name: 'BFA / MFA Peers', value: (15 / 201) },
    { name: 'Cold Contacting Spaces', value: (12 / 201) },
    { name: 'Contacts from Facebook', value: (11 / 201) },
    { name: 'Contacts from Instagram', value: (27 / 201) },
    { name: 'Direct Contact At An Art Center', value: (1 / 201) },
    { name: 'Direct Emails from Gallerists / Curators', value: (23 / 201) },
    { name: 'Friends', value: (1 / 201) },
    { name: 'Gallery Represented', value: (1 / 201) },
    { name: 'Group Invitationals', value: (1 / 201) },
    { name: 'N/A', value: (2 / 201) },
    { name: 'Open Call On Instagram', value: (1 / 201) },
    { name: 'Other Artists', value: (50 / 201) },
    { name: 'Relationships With Spaces', value: (1 / 201) },
    { name: 'Structured Applications', value: (37 / 201) },
    { name: 'Open Calls', value: (37 / 201) },
    { name: 'Teachers / Faculty', value: (15 / 201) },
]

export const SOCMEDIA_FEATURES = [
  { name: "Not Sure / Hard to Say", value: "0.071" },
  { name: "0", value: "0.163" },
  { name: "1-2", value: "0.214" },
  { name: "3-5", value: "0.265" },
  { name: "6-10", value: "0.071" },
  { name: "11-25", value: "0.112" },
  { name: "25+", value: "0.102" },
]

export const PUBLICATION_COUNT = [
  { name: "0", value: "0.584" },
  { name: "1-2", value: "0.287" },
  { name: "3-5", value: "0.099" },
  { name: "6-10", value: "0.02" },
  { name: "11-25", value: "0" },
  { name: "25+", value: "0.01" },
]

export const APPLICATION_FEES = [
  { name: "Not Sure / Hard to Say", value: "0.01" },
  { name: "$0", value: "0.44" },
  { name: "$0-$25", value: "0.08" },
  { name: "$25-$50", value: "0.13" },
  { name: "$50-$100", value: "0.13" },
  { name: "$100-$250", value: "0.15" },
  { name: "$250+", value: "0.06" },
];

export const SHOW_APPLICATIONS = [
  { name: "0", value: "0.416" },
  { name: "1-2", value: "0.178" },
  { name: "3-5", value: "0.218" },
  { name: "6-10", value: "0.139" },
  { name: "11-25", value: "0.03" },
  { name: "25+", value: "0.02" },
];

export const SOLO_EXHIBITIONS_COUNT = [
  { name: "0", value: "0.673" },
  { name: "1-2", value: "0.297" },
  { name: "3-5", value: "0.3" },
];

export const GROUP_EXHIBITIONS_COUNT = [
  { name: "0", value: "0.228" },
  { name: "1-2", value: "0.475" },
  { name: "3-5", value: "0.218" },
  { name: "6-10", value: "0.079" },
];

export const EXHIBITIONS_PRIORITY = [
  { name: "Extremely Important", value: "0.218" },
  { name: "Somewhat Important", value: "0.465" },
  { name: "Not Important", value: "0.228" },
  { name: "Not Sure / Hard to Say", value: "0.079" },
];

export const RACE = [
  { name: "Decline to Answer", value: "0.04" },
  { name: "White / Caucasian", value: "0.73" },
  { name: "Biracial / Multi Racial", value: "0.07" },
  { name: "Asian / Asian American", value: "0.04" },
  { name: "Black / African American", value: "0.04" },
  { name: "Jewish / White", value: "0.03" },
  { name: "Latino / Latina / Latinx", value: "0.03" },
  { name: "Iranian", value: "0.01" },
  { name: "Native American", value: "0.01" },
];

export const GENDER = [
  { name: "Other", value: "0.005" },
  { name: "Non-Binary", value: "0.08" },
  { name: "Male", value: "0.32" },
  { name: "Female", value: "0.58" },
];

export const AGE = [
  { name: "<18", value: "0.06" },
  { name: "18-29", value: "0.32" },
  { name: "30-39", value: "0.26" },
  { name: "40-49", value: "0.07" },
  { name: "50-59", value: "0.09" },
  { name: "60-69", value: "0.14" },
  { name: "70+", value: "0.06" },
];

export const ORIENTATION = [
  { name: "Yes", value: "0.564" },
  { name: "No", value: "0.356" },
  { name: "Decline to Say", value: "0.079" },
];

export const FOUND_SURVEY = [
  { name: "artist / peer", value: "0.198" },
  { name: "instagram", value: "0.733" },
  { name: "other", value: "0.069" },
];

export const KEYWORDS = [
  { name: "Abstract", value: 23 },
  { name: "Abstracted", value: 1 },
  { name: "Abstraction", value: 5 },
  { name: "Acid", value: 1 },
  { name: "Acrylic", value: 11 },
  { name: "Acrylics", value: 1 },
  { name: "Aesthetics", value: 1 },
  { name: "Age", value: 1 },
  { name: "Alien", value: 1 },
  { name: "Allegorical", value: 1 },
  { name: "Altars", value: 1 },
  { name: "Altered", value: 1 },
  { name: "Anatomy", value: 1 },
  { name: "Anger", value: 1 },
  { name: "Animal", value: 1 },
  { name: "Animals", value: 1 },
  { name: "Animation", value: 3 },
  { name: "Anthropomorphic", value: 1 },
  { name: "Art", value: 4 },
  { name: "Archetypes", value: 1 },
  { name: "Architectural", value: 1 },
  { name: "Artist", value: 1 },
  { name: "Arts", value: 1 },
  { name: "Assemblage", value: 1 },
  { name: "Astrology", value: 1 },
  { name: "Authentic", value: 1 },
  { name: "Auto", value: 1 },
  { name: "Background", value: 1 },
  { name: "Banality", value: 1 },
  { name: "Baroque", value: 1 },
  { name: "Based", value: 1 },
  { name: "Biology", value: 1 },
  { name: "Biomorphic", value: 1 },
  { name: "Black", value: 1 },
  { name: "Board", value: 1 },
  { name: "Body", value: 1 },
  { name: "Bold", value: 1 },
  { name: "Books", value: 1 },
  { name: "Botanical", value: 2 },
  { name: "Bright", value: 9 },
  { name: "Brush", value: 1 },
  { name: "Brutality", value: 1 },
  { name: "Building", value: 1 },
  { name: "Carving", value: 1 },
  { name: "Ceramic", value: 1 },
  { name: "Chance", value: 1 },
  { name: "Change", value: 1 },
  { name: "Character", value: 1 },
  { name: "Characters", value: 1 },
  { name: "Charcoal", value: 3 },
  { name: "Caricatures", value: 1 },
  { name: "Cinematic", value: 1 },
  { name: "Classical", value: 2 },
  { name: "Clay", value: 1 },
  { name: "Climate", value: 1 },
  { name: "Cold", value: 2 },
  { name: "Collage", value: 4 },
  { name: "Colo", value: 1 },
  { name: "Color", value: 14 },
  { name: "Colored", value: 1 },
  { name: "Colorful", value: 14 },
  { name: "Colorist", value: 1 },
  { name: "Colors", value: 5 },
  { name: "Colour", value: 2 },
  { name: "Comic", value: 1 },
  { name: "Conceptua", value: 1 },
  { name: "Conceptual", value: 4 },
  { name: "Concerns", value: 1 },
  { name: "Concrete", value: 1 },
  { name: "Confrontational", value: 1 },
  { name: "Connections", value: 1 },
  { name: "Consciousness", value: 1 },
  { name: "Contemporary", value: 5 },
  { name: "Contour", value: 1 },
  { name: "Contrasting", value: 1 },
  { name: "Cosmic", value: 1 },
  { name: "Craft", value: 1 },
  { name: "Cultural", value: 1 },
  { name: "Cyberpunk", value: 1 },
  { name: "Dark", value: 1 },
  { name: "Depth", value: 1 },
  { name: "Design", value: 3 },
  { name: "Detailed", value: 1 },
  { name: "Different", value: 1 },
  { name: "Digital", value: 4 },
  { name: "Discord", value: 1 },
  { name: "Discrimination", value: 1 },
  { name: "Disfigured", value: 1 },
  { name: "Divide", value: 1 },
  { name: "Documentary", value: 1 },
  { name: "Dot", value: 1 },
  { name: "Drama", value: 1 },
  { name: "Drawing", value: 14 },
  { name: "Drawings", value: 2 },
  { name: "Dreams", value: 1 },
  { name: "Dynami", value: 1 },
  { name: "Dystopia", value: 1 },
  { name: "Earth", value: 1 },
  { name: "Earthy", value: 1 },
  { name: "Ecology", value: 3 },
  { name: "Edgy", value: 1 },
  { name: "Education", value: 1 },
  { name: "Embodiment", value: 1 },
  { name: "Emotional", value: 1 },
  { name: "Emphasis", value: 1 },
  { name: "Endangered", value: 1 },
  { name: "Endurance", value: 1 },
  { name: "Environmental", value: 3 },
  { name: "Ephemeral", value: 1 },
  { name: "Erotic", value: 1 },
  { name: "Ethnography", value: 1 },
  { name: "Existential", value: 2 },
  { name: "Experimenta", value: 1 },
  { name: "Experimental", value: 2 },
  { name: "Exploration", value: 2 },
  { name: "Explorations", value: 1 },
  { name: "Expression", value: 1 },
  { name: "Expressionist", value: 1 },
  { name: "Expressionistic", value: 1 },
  { name: "Expressive", value: 4 },
  { name: "Family", value: 1 },
  { name: "Fan", value: 1 },
  { name: "Fantastical", value: 1 },
  { name: "Fantasy", value: 1 },
  { name: "Fears", value: 1 },
  { name: "Feeling", value: 1 },
  { name: "Fiber", value: 1 },
  { name: "Fibers", value: 1 },
  { name: "Fiction", value: 2 },
  { name: "Field", value: 1 },
  { name: "Figurative", value: 21 },
  { name: "Film", value: 1 },
  { name: "Finishes", value: 1 },
  { name: "Flashe", value: 1 },
  { name: "Folk", value: 1 },
  { name: "Form", value: 3 },
  { name: "Formal", value: 2 },
  { name: "Fragile", value: 1 },
  { name: "Fun", value: 1 },
  { name: "Functional", value: 1 },
  { name: "Game", value: 2 },
  { name: "Geometric", value: 2 },
  { name: "Glaze", value: 1 },
  { name: "Gouache", value: 1 },
  { name: "Graphic", value: 2 },
  { name: "Graphite", value: 7 },
  { name: "Grotesque", value: 1 },
  { name: "Hairy", value: 1 },
  { name: "Hard", value: 1 },
  { name: "Harmony", value: 2 },
  { name: "Hate", value: 1 },
  { name: "Healing", value: 1 },
  { name: "Health", value: 2 },
  { name: "High", value: 1 },
  { name: "High Chroma", value: 1 },
  { name: "History", value: 2 },
  { name: "Hope", value: 1 },
  { name: "Horror", value: 1 },
  { name: "Hubris", value: 1 },
  { name: "Human", value: 3 },
  { name: "Humorou", value: 1 },
  { name: "Hurt", value: 1 },
  { name: "Illustration", value: 2 },
  { name: "Image", value: 1 },
  { name: "Imaginative", value: 1 },
  { name: "Ink", value: 6 },
  { name: "Inking", value: 1 },
  { name: "Intaglio", value: 1 },
  { name: "Interactions", value: 1 },
  { name: "Interactive", value: 2 },
  { name: "Interdisciplinar", value: 2 },
  { name: "Interdisciplinary", value: 7 },
  { name: "Intimacy", value: 1 },
  { name: "Intimate", value: 1 },
  { name: "Introspective", value: 1 },
  { name: "Intuitive", value: 2 },
  { name: "Irreverent", value: 1 },
  { name: "Issue", value: 1 },
  { name: "Issues", value: 9 },
  { name: "Japanese", value: 1 },
  { name: "Justice", value: 1 },
  { name: "Knife", value: 1 },
  { name: "Landscape", value: 7 },
  { name: "Large-Scale", value: 1 },
  { name: "Layered", value: 1 },
  { name: "Layering", value: 1 },
  { name: "Life", value: 3 },
  { name: "Light", value: 2 },
  { name: "Line", value: 1 },
  { name: "Linear", value: 1 },
  { name: "Literary", value: 1 },
  { name: "Loneliness", value: 1 },
  { name: "Loss", value: 1 },
  { name: "Love", value: 2 },
  { name: "Luminous", value: 1 },
  { name: "Magic", value: 1 },
  { name: "Manga", value: 1 },
  { name: "Markers", value: 1 },
  { name: "Material", value: 1 },
  { name: "Materialit", value: 1 },
  { name: "Mathematics", value: 1 },
  { name: "Mature", value: 1 },
  { name: "Maximalism", value: 1 },
  { name: "Media", value: 3 },
  { name: "Medias", value: 1 },
  { name: "Medium/Large", value: 1 },
  { name: "Mediums", value: 1 },
  { name: "Memory", value: 2 },
  { name: "Mental", value: 2 },
  { name: "Metal", value: 2 },
  { name: "Minimal", value: 2 },
  { name: "Minimalis", value: 1 },
  { name: "Minimalism", value: 2 },
  { name: "Minimalist", value: 1 },
  { name: "Minority", value: 1 },
  { name: "Misunderstood", value: 1 },
  { name: "Mix", value: 1 },
  { name: "Mixed-Media", value: 16 },
  { name: "Monochrome", value: 1 },
  { name: "Monotone", value: 1 },
  { name: "Moody", value: 1 },
  { name: "Motion", value: 1 },
  { name: "Multi", value: 1 },
  { name: "Multi-Disciplinary", value: 1 },
  { name: "Multicolors", value: 1 },
  { name: "Multidisciplinary", value: 1 },
  { name: "Multimedia", value: 1 },
  { name: "Multiple", value: 1 },
  { name: "Multiples", value: 1 },
  { name: "Mural", value: 1 },
  { name: "Music", value: 1 },
  { name: "Mute", value: 1 },
  { name: "Muted", value: 2 },
  { name: "Mystical", value: 1 },
  { name: "Mysticism", value: 2 },
  { name: "Myth", value: 2 },
  { name: "Mythology", value: 1 },
  { name: "Narration", value: 1 },
  { name: "Narrative", value: 5 },
  { name: "Natural", value: 1 },
  { name: "Nature", value: 4 },
  { name: "Neon", value: 1 },
  { name: "Neons", value: 1 },
  { name: "New", value: 1 },
  { name: "Night", value: 1 },
  { name: "Non-Objective", value: 2 },
  { name: "Nostalgic", value: 1 },
  { name: "Obscurification", value: 1 },
  { name: "Obsolete", value: 1 },
  { name: "Often", value: 1 },
  { name: "Oil", value: 15 },
  { name: "Oils", value: 1 },
  { name: "Opaque", value: 1 },
  { name: "Organic", value: 3 },
  { name: "Others", value: 1 },
  { name: "Outlet", value: 1 },
  { name: "Pain", value: 1 },
  { name: "Paint", value: 9 },
  { name: "Painter", value: 2 },
  { name: "Painterly", value: 2 },
  { name: "Painting", value: 19 },
  { name: "Paintings", value: 4 },
  { name: "Paints", value: 2 },
  { name: "Palette", value: 1 },
  { name: "Panel", value: 1 },
  { name: "Paper", value: 6 },
  { name: "Pastel", value: 1 },
  { name: "Pattern", value: 1 },
  { name: "Patterned", value: 1 },
  { name: "Pen", value: 1 },
  { name: "Pencil", value: 3 },
  { name: "Penciled", value: 1 },
  { name: "Pencils", value: 1 },
  { name: "Performance", value: 1 },
  { name: "Performative", value: 1 },
  { name: "Performativity", value: 1 },
  { name: "Personal", value: 4 },
  { name: "Photo", value: 2 },
  { name: "Photograph", value: 1 },
  { name: "Photography", value: 7 },
  { name: "Photoremi", value: 1 },
  { name: "Pink", value: 1 },
  { name: "Plants", value: 2 },
  { name: "Pluralism", value: 1 },
  { name: "Poetics", value: 1 },
  { name: "Polish", value: 1 },
  { name: "Political", value: 4 },
  { name: "Pop", value: 1 },
  { name: "Portrait", value: 3 },
  { name: "Portraits", value: 3 },
  { name: "Portraiture", value: 1 },
  { name: "Precious", value: 1 },
  { name: "Press", value: 1 },
  { name: "Print", value: 1 },
  { name: "Printmaking", value: 5 },
  { name: "Prints", value: 1 },
  { name: "Processing", value: 1 },
  { name: "Provoking", value: 1 },
  { name: "Psyche", value: 1 },
  { name: "Psychoanalytical", value: 1 },
  { name: "Psychology", value: 2 },
  { name: "Queer", value: 2 },
  { name: "Questions", value: 1 },
  { name: "Quiet", value: 1 },
  { name: "Racial", value: 1 },
  { name: "Realism", value: 2 },
  { name: "Realist", value: 1 },
  { name: "Realistic", value: 2 },
  { name: "Reality", value: 1 },
  { name: "Relational", value: 1 },
  { name: "Relationships", value: 1 },
  { name: "Religion", value: 1 },
  { name: "Representation", value: 1 },
  { name: "Representational", value: 2 },
  { name: "Repurpose", value: 1 },
  { name: "Research", value: 2 },
  { name: "Responsibility", value: 1 },
  { name: "Rights", value: 2 },
  { name: "Saturation", value: 1 },
  { name: "Scale", value: 1 },
  { name: "Schizophrenia", value: 1 },
  { name: "School", value: 1 },
  { name: "Sci-Fi", value: 2 },
  { name: "Science", value: 5 },
  { name: "Scissor", value: 1 },
  { name: "Screen", value: 1 },
  { name: "Screenprinting", value: 1 },
  { name: "Sculptor", value: 1 },
  { name: "Sculpture", value: 10 },
  { name: "Sculptural", value: 3 },
  { name: "Sculptures", value: 1 },
  { name: "Semi-Abstract", value: 1 },
  { name: "Semi-Realism", value: 1 },
  { name: "Series", value: 1 },
  { name: "Sexual", value: 1 },
  { name: "Shapes", value: 3 },
  { name: "Silhouette", value: 1 },
  { name: "Single", value: 1 },
  { name: "Sketch", value: 1 },
  { name: "Social", value: 10 },
  { name: "Society", value: 2 },
  { name: "Socio-Political", value: 1 },
  { name: "Soft", value: 1 },
  { name: "Sound", value: 2 },
  { name: "Space", value: 3 },
  { name: "Spectrality", value: 1 },
  { name: "Spiritual", value: 5 },
  { name: "Spirituality", value: 1 },
  { name: "Steampunk", value: 1 },
  { name: "Still", value: 2 },
  { name: "Still-Life", value: 2 },
  { name: "Stitching", value: 1 },
  { name: "Story", value: 2 },
  { name: "Stream", value: 1 },
  { name: "Styleless", value: 1 },
  { name: "Styles", value: 1 },
  { name: "Stylized", value: 2 },
  { name: "Subject", value: 1 },
  { name: "Subjugation", value: 1 },
  { name: "Supremacy", value: 1 },
  { name: "Surreal", value: 2 },
  { name: "Surrealism", value: 2 },
  { name: "Surrealist", value: 2 },
  { name: "Symbolism", value: 1 },
  { name: "Taking", value: 1 },
  { name: "Tattoo", value: 1 },
  { name: "Technical", value: 1 },
  { name: "Technique", value: 1 },
  { name: "Techno", value: 1 },
  { name: "Telling", value: 1 },
  { name: "Tension", value: 1 },
  { name: "Text", value: 1 },
  { name: "Textile", value: 1 },
  { name: "Textiles", value: 1 },
  { name: "Textural", value: 1 },
  { name: "Texture", value: 1 },
  { name: "Theme", value: 1 },
  { name: "Theory", value: 1 },
  { name: "Thought", value: 1 },
  { name: "Tonalism", value: 1 },
  { name: "Tones", value: 1 },
  { name: "Traditional", value: 2 },
  { name: "Trangender", value: 1 },
  { name: "Trans", value: 1 },
  { name: "Transfer", value: 1 },
  { name: "Transien", value: 1 },
  { name: "Transparency", value: 1 },
  { name: "Unconventional", value: 1 },
  { name: "Underdeveloped", value: 1 },
  { name: "Unique", value: 1 },
  { name: "Unstable", value: 1 },
  { name: "Urban", value: 1 },
  { name: "Variety", value: 1 },
  { name: "Vector", value: 1 },
  { name: "Vectors", value: 1 },
  { name: "Video", value: 2 },
  { name: "Views", value: 1 },
  { name: "Vintage", value: 1 },
  { name: "Visibility", value: 1 },
  { name: "Visual", value: 1 },
  { name: "Vivid", value: 2 },
  { name: "Water", value: 3 },
  { name: "Watercolor", value: 5 },
  { name: "Watercolour", value: 1 },
  { name: "Wax", value: 1 },
  { name: "Wearable", value: 1 },
  { name: "Weaving", value: 1 },
  { name: "Web", value: 1 },
  { name: "Whimsical", value: 1 },
  { name: "White", value: 1 },
  { name: "Women", value: 1 },
  { name: "Woo", value: 1 },
  { name: "Wood", value: 3 },
  { name: "Words", value: 1 },
  { name: "Works", value: 1 },
  { name: "World", value: 1 },
  { name: "Writing", value: 1 },
  { name: "Zines", value: 2 },
];


export const EXHIBITION_SPACES = [
  { name: "Art Center", value: 1 },
  { name: "Art Fair", value: 1 },
  { name: "Art School Galleries", value: 1 },
  { name: "Art Walks", value: 1 },
  { name: "Artist Run Spaces", value: 44 },
  { name: "Beauty Salons", value: 1 },
  { name: "Book Fairs", value: 2 },
  { name: "Church", value: 1 },
  { name: "Co-op Spaces", value: 12 },
  { name: "Coffee Shops", value: 16 },
  { name: "College Gallery", value: 1 },
  { name: "Furniture Store", value: 1 },
  { name: "Gallery Spaces", value: 52 },
  { name: "Library", value: 1 },
  { name: "Museum Spaces", value: 19 },
  { name: "None", value: 1 },
  { name: "Nonprofit Wellness / Creative Center", value: 1 },
  { name: "Open Studio", value: 2 },
  { name: "Outdoor Spaces", value: 10 },
  { name: "Podcast Episode", value: 1 },
  { name: "Pop-Up Spaces", value: 16 },
  { name: "Public Spaces", value: 25 },
  { name: "Restaurants", value: 2 },
  { name: "School", value: 1 },
  { name: "Schools", value: 1 },
  { name: "State Fair", value: 1 },
  { name: "Tavern", value: 1 },
  { name: "Theater", value: 1 },
  { name: "Universities and Colleges", value: 1 },
]